import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { Frame, Download } from "lucide-react";

const boundaries = [
  { id: "upstream", label: "Upstream inflow (m³/s)", min: 0, max: 50, step: 0.5, default: 10 },
  { id: "downstream", label: "Downstream water level (m)", min: 0, max: 5, step: 0.1, default: 2 },
  { id: "rainfall", label: "Rainfall intensity (mm/hr)", min: 0, max: 100, step: 5, default: 30 },
  { id: "gwLevel", label: "Groundwater level (m below)", min: 0, max: 10, step: 0.5, default: 3 },
  { id: "tideRange", label: "Tidal range (m)", min: 0, max: 4, step: 0.1, default: 0 },
];

export const BoundaryConditionLab = () => {
  const [values, setValues] = useState<Record<string, number>>(
    Object.fromEntries(boundaries.map((b) => [b.id, b.default]))
  );

  const totalHead = values.upstream * 0.3 + values.downstream + values.gwLevel * 0.2 + values.tideRange * 0.5;
  const peakFlow = values.upstream + values.rainfall * 0.15 * (1 + values.tideRange * 0.2);
  const backwaterRisk = values.downstream > 3 || values.tideRange > 2;
  const gwInteraction = values.gwLevel < 2;

  const barData = [
    { label: "Upstream", value: values.upstream, max: 50, color: "bg-blue-500" },
    { label: "Downstream", value: values.downstream, max: 5, color: "bg-cyan-500" },
    { label: "Rainfall", value: values.rainfall, max: 100, color: "bg-sky-500" },
    { label: "GW Level", value: values.gwLevel, max: 10, color: "bg-teal-500" },
    { label: "Tidal", value: values.tideRange, max: 4, color: "bg-indigo-500" },
  ];

  const exportReport = () => {
    const lines = [
      "BOUNDARY CONDITION ASSESSMENT",
      "=============================",
      "",
      ...boundaries.map((b) => `${b.label}: ${values[b.id]}`),
      "",
      `Estimated Peak Flow: ${peakFlow.toFixed(1)} m³/s`,
      `Total Hydraulic Head: ${totalHead.toFixed(1)} m`,
      `Backwater Risk: ${backwaterRisk ? "YES" : "No"}`,
      `GW Interaction: ${gwInteraction ? "YES — coupled model needed" : "Negligible"}`,
      "",
      "Generated by Rules for Responsible Modeling — Ch.7 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "boundary-conditions.txt";
    a.click();
    toast.success("Boundary assessment downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-teal-500 to-cyan-500 text-white">
          <Frame className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Boundary Condition Lab</h2>
          <Badge variant="outline">Chapter 7</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Set boundary conditions and watch how they interact to affect model behavior.</p>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-5">
          {boundaries.map((b) => (
            <div key={b.id}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-foreground font-medium">{b.label}</span>
                <span className="text-primary font-bold">{values[b.id]}</span>
              </div>
              <Slider min={b.min} max={b.max} step={b.step} value={[values[b.id]]} onValueChange={([v]) => setValues((p) => ({ ...p, [b.id]: v }))} />
            </div>
          ))}
        </Card>

        <div className="space-y-4">
          <Card className="p-5">
            <p className="text-sm font-bold text-foreground mb-3">Boundary Contribution</p>
            {barData.map((b) => (
              <div key={b.label} className="flex items-center gap-2 mb-2">
                <span className="text-xs text-muted-foreground w-20">{b.label}</span>
                <div className="flex-1 h-3 bg-secondary rounded-full overflow-hidden">
                  <div className={`h-full ${b.color} rounded-full transition-all`} style={{ width: `${(b.value / b.max) * 100}%` }} />
                </div>
              </div>
            ))}
          </Card>

          <Card className="p-5 text-center">
            <p className="text-xs text-muted-foreground">Estimated Peak Flow</p>
            <p className="text-3xl font-black text-foreground">{peakFlow.toFixed(1)} <span className="text-sm font-normal">m³/s</span></p>
          </Card>

          <div className="flex gap-3">
            {backwaterRisk && (
              <Badge variant="destructive" className="text-xs">⚠ Backwater Risk</Badge>
            )}
            {gwInteraction && (
              <Badge variant="secondary" className="text-xs">💧 GW Interaction</Badge>
            )}
            {values.tideRange > 0 && (
              <Badge variant="outline" className="text-xs">🌊 Tidal Influence</Badge>
            )}
          </div>

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Boundary Report
          </Button>
        </div>
      </div>
    </div>
  );
};
