import { useState, useCallback } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { Target, Download, RotateCcw } from "lucide-react";

// Synthetic "observed" data
const observed = [0, 2, 8, 25, 45, 38, 22, 12, 6, 3, 1, 0];
const timeLabels = Array.from({ length: 12 }, (_, i) => `${i}h`);

const params = [
  { id: "peakScale", label: "Peak scaling factor", min: 0.2, max: 2, step: 0.05, default: 1 },
  { id: "timing", label: "Timing offset (hours)", min: -3, max: 3, step: 0.5, default: 0 },
  { id: "baseflow", label: "Baseflow (m³/s)", min: 0, max: 10, step: 0.5, default: 0 },
  { id: "recession", label: "Recession rate", min: 0.3, max: 1.5, step: 0.05, default: 1 },
];

export const CalibrationCoach = () => {
  const [values, setValues] = useState<Record<string, number>>(
    Object.fromEntries(params.map((p) => [p.id, p.default]))
  );
  const [attempts, setAttempts] = useState(0);

  const simulated = observed.map((_, i) => {
    const shifted = i - values.timing;
    const idx = Math.round(shifted);
    const base = idx >= 0 && idx < observed.length ? observed[idx] : 0;
    return Math.max(0, base * values.peakScale * values.recession + values.baseflow);
  });

  const meanObs = observed.reduce((s, v) => s + v, 0) / observed.length;
  const ssRes = observed.reduce((s, v, i) => s + (v - simulated[i]) ** 2, 0);
  const ssTot = observed.reduce((s, v) => s + (v - meanObs) ** 2, 0);
  const nse = ssTot > 0 ? 1 - ssRes / ssTot : 0;
  const nsePct = Math.round(nse * 100);

  const maxVal = Math.max(...observed, ...simulated);
  const svgW = 400;
  const svgH = 180;
  const barW = svgW / observed.length - 4;

  const reset = useCallback(() => {
    setValues(Object.fromEntries(params.map((p) => [p.id, p.default])));
    setAttempts(0);
  }, []);

  const handleChange = (id: string, v: number) => {
    setValues((p) => ({ ...p, [id]: v }));
    setAttempts((a) => a + 1);
  };

  const nseColor = nse >= 0.75 ? "text-green-500" : nse >= 0.5 ? "text-yellow-500" : "text-red-500";
  const rating = nse >= 0.9 ? "Excellent!" : nse >= 0.75 ? "Good" : nse >= 0.5 ? "Acceptable" : nse >= 0 ? "Poor" : "Negative — wrong direction";

  const exportReport = () => {
    const lines = [
      "CALIBRATION RESULTS",
      "===================",
      "",
      ...params.map((p) => `${p.label}: ${values[p.id]}`),
      "",
      `NSE: ${nse.toFixed(3)} (${rating})`,
      `Calibration attempts: ${attempts}`,
      "",
      "Generated by Rules for Responsible Modeling — Ch.8 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "calibration-results.txt";
    a.click();
    toast.success("Calibration results downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-amber-500 to-orange-500 text-white">
          <Target className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Calibration Coach</h2>
          <Badge variant="outline">Chapter 8</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Adjust parameters to match the simulated hydrograph (blue) to the observed (gray). Minimize the gap!</p>

      <Card className="p-5">
        <svg viewBox={`0 0 ${svgW} ${svgH}`} className="w-full">
          {observed.map((v, i) => (
            <rect key={`obs-${i}`} x={i * (barW + 4) + 2} y={svgH - (v / maxVal) * svgH} width={barW / 2} height={(v / maxVal) * svgH} fill="hsl(var(--muted-foreground))" opacity={0.3} rx={2} />
          ))}
          {simulated.map((v, i) => (
            <rect key={`sim-${i}`} x={i * (barW + 4) + barW / 2 + 2} y={svgH - (v / maxVal) * svgH} width={barW / 2} height={(v / maxVal) * svgH} fill="hsl(var(--primary))" opacity={0.8} rx={2} />
          ))}
        </svg>
        <div className="flex gap-4 justify-center mt-2 text-xs text-muted-foreground">
          <span className="flex items-center gap-1"><span className="w-3 h-3 bg-muted-foreground/30 rounded-sm inline-block" /> Observed</span>
          <span className="flex items-center gap-1"><span className="w-3 h-3 bg-primary/80 rounded-sm inline-block" /> Simulated</span>
        </div>
      </Card>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-5">
          {params.map((p) => (
            <div key={p.id}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-foreground font-medium">{p.label}</span>
                <span className="text-primary font-bold">{values[p.id]}</span>
              </div>
              <Slider min={p.min} max={p.max} step={p.step} value={[values[p.id]]} onValueChange={([v]) => handleChange(p.id, v)} />
            </div>
          ))}
          <Button variant="outline" size="sm" onClick={reset} className="gap-2"><RotateCcw className="w-3 h-3" /> Reset</Button>
        </Card>

        <div className="space-y-4">
          <Card className="p-6 text-center">
            <p className="text-xs text-muted-foreground">Nash-Sutcliffe Efficiency</p>
            <p className={`text-5xl font-black ${nseColor}`}>{nse.toFixed(2)}</p>
            <p className="text-sm text-muted-foreground mt-1">{rating}</p>
            <p className="text-xs text-muted-foreground mt-3">Attempts: {attempts}</p>
          </Card>

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Results
          </Button>
        </div>
      </div>
    </div>
  );
};
