import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Database, Download, CheckCircle2, XCircle } from "lucide-react";

const auditCriteria = [
  { id: "source", label: "Data source documented", weight: 10 },
  { id: "period", label: "Period of record stated", weight: 8 },
  { id: "gaps", label: "Missing data quantified", weight: 9 },
  { id: "qc", label: "Quality control applied", weight: 10 },
  { id: "units", label: "Units verified & consistent", weight: 7 },
  { id: "spatial", label: "Spatial coverage adequate", weight: 8 },
  { id: "temporal", label: "Temporal resolution sufficient", weight: 9 },
  { id: "metadata", label: "Metadata complete", weight: 6 },
  { id: "uncertainty", label: "Measurement uncertainty noted", weight: 10 },
  { id: "backup", label: "Raw data archived", weight: 5 },
];

const dataTypes = ["Rainfall", "Flow", "Topography", "Land Use", "Soil"];

export const DataAuditScorer = () => {
  const [selectedType, setSelectedType] = useState("Rainfall");
  const [checks, setChecks] = useState<Record<string, boolean>>({});

  const toggle = (id: string) => setChecks((p) => ({ ...p, [`${selectedType}-${id}`]: !p[`${selectedType}-${id}`] }));

  const score = auditCriteria.reduce((sum, c) => sum + (checks[`${selectedType}-${c.id}`] ? c.weight : 0), 0);
  const maxScore = auditCriteria.reduce((s, c) => s + c.weight, 0);
  const pct = Math.round((score / maxScore) * 100);
  const grade = pct >= 90 ? "A" : pct >= 75 ? "B" : pct >= 60 ? "C" : pct >= 40 ? "D" : "F";
  const gradeColor = pct >= 75 ? "text-green-500" : pct >= 50 ? "text-yellow-500" : "text-red-500";

  const overallScores = dataTypes.map((dt) => {
    const s = auditCriteria.reduce((sum, c) => sum + (checks[`${dt}-${c.id}`] ? c.weight : 0), 0);
    return { type: dt, score: s, pct: Math.round((s / maxScore) * 100) };
  });
  const overallPct = Math.round(overallScores.reduce((s, o) => s + o.pct, 0) / dataTypes.length);

  const exportReport = () => {
    const lines = [
      "DATA AUDIT REPORT",
      "=================",
      "",
      ...overallScores.map((o) => `${o.type}: ${o.pct}% (${o.score}/${maxScore})`),
      "",
      `Overall Data Readiness: ${overallPct}%`,
      "",
      "Generated by Rules for Responsible Modeling — Ch.3 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "data-audit-report.txt";
    a.click();
    toast.success("Data audit report downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 text-white">
          <Database className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Data Audit Scorer</h2>
          <Badge variant="outline">Chapter 3</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Check off quality criteria for each data type to see your overall data readiness score.</p>

      <div className="flex gap-2 flex-wrap">
        {dataTypes.map((dt) => (
          <Button key={dt} size="sm" variant={selectedType === dt ? "default" : "outline"} onClick={() => setSelectedType(dt)}>
            {dt}
          </Button>
        ))}
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-5 space-y-2">
          {auditCriteria.map((c) => {
            const checked = !!checks[`${selectedType}-${c.id}`];
            return (
              <button key={c.id} onClick={() => toggle(c.id)} className={`w-full flex items-center gap-3 p-2.5 rounded-lg transition-colors text-left ${checked ? "bg-primary/10" : "hover:bg-muted"}`}>
                {checked ? <CheckCircle2 className="w-5 h-5 text-primary shrink-0" /> : <XCircle className="w-5 h-5 text-muted-foreground/40 shrink-0" />}
                <span className={`text-sm ${checked ? "text-foreground" : "text-muted-foreground"}`}>{c.label}</span>
                <Badge variant="secondary" className="ml-auto text-[10px]">+{c.weight}</Badge>
              </button>
            );
          })}
        </Card>

        <div className="space-y-4">
          <Card className="p-6 text-center">
            <p className="text-sm text-muted-foreground mb-1">{selectedType} Quality Grade</p>
            <div className={`text-6xl font-black ${gradeColor}`}>{grade}</div>
            <p className="text-lg font-bold text-foreground mt-1">{pct}%</p>
            <div className="w-full h-3 bg-secondary rounded-full overflow-hidden mt-3">
              <div className="h-full bg-primary transition-all rounded-full" style={{ width: `${pct}%` }} />
            </div>
          </Card>

          <Card className="p-5">
            <p className="text-sm font-bold text-foreground mb-3">All Data Types</p>
            {overallScores.map((o) => (
              <div key={o.type} className="flex items-center gap-2 mb-2">
                <span className="text-xs text-muted-foreground w-20">{o.type}</span>
                <div className="flex-1 h-2 bg-secondary rounded-full overflow-hidden">
                  <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${o.pct}%` }} />
                </div>
                <span className="text-xs font-bold w-8 text-right">{o.pct}%</span>
              </div>
            ))}
            <p className="text-xs text-muted-foreground mt-3 pt-2 border-t">Overall readiness: <strong className="text-foreground">{overallPct}%</strong></p>
          </Card>

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Audit Report
          </Button>
        </div>
      </div>
    </div>
  );
};
