import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { GitBranch, Download } from "lucide-react";

const criteria = [
  { id: "catchmentSize", label: "Catchment size (km²)", min: 0.1, max: 500, step: 0.1, default: 10 },
  { id: "dataAvail", label: "Data availability (1-10)", min: 1, max: 10, step: 1, default: 5 },
  { id: "accuracy", label: "Required accuracy (1-10)", min: 1, max: 10, step: 1, default: 5 },
  { id: "budget", label: "Budget level (1-10)", min: 1, max: 10, step: 1, default: 5 },
  { id: "urbanPct", label: "% Urbanized", min: 0, max: 100, step: 5, default: 30 },
];

const models = [
  { name: "Rational Method", type: "Empirical", complexity: 1, minData: 1, bestUrban: [0, 40], bestSize: [0, 5] },
  { name: "Unit Hydrograph", type: "Conceptual", complexity: 3, minData: 3, bestUrban: [0, 60], bestSize: [1, 100] },
  { name: "EPA SWMM", type: "Physics-based", complexity: 7, minData: 5, bestUrban: [30, 100], bestSize: [0.1, 50] },
  { name: "HEC-HMS", type: "Conceptual", complexity: 5, minData: 4, bestUrban: [0, 80], bestSize: [5, 500] },
  { name: "MIKE SHE", type: "Physics-based", complexity: 9, minData: 7, bestUrban: [0, 100], bestSize: [10, 500] },
  { name: "InfoWorks ICM", type: "Physics-based", complexity: 8, minData: 6, bestUrban: [40, 100], bestSize: [0.1, 100] },
];

export const ModelSelector = () => {
  const [values, setValues] = useState<Record<string, number>>(
    Object.fromEntries(criteria.map((c) => [c.id, c.default]))
  );

  const ranked = models.map((m) => {
    let score = 0;
    const size = values.catchmentSize;
    if (size >= m.bestSize[0] && size <= m.bestSize[1]) score += 25;
    else score += Math.max(0, 15 - Math.abs(size - (m.bestSize[0] + m.bestSize[1]) / 2) * 0.1);

    const urban = values.urbanPct;
    if (urban >= m.bestUrban[0] && urban <= m.bestUrban[1]) score += 20;

    if (values.dataAvail >= m.minData) score += 20;
    else score += Math.max(0, 20 - (m.minData - values.dataAvail) * 5);

    if (values.accuracy <= m.complexity + 2 && values.accuracy >= m.complexity - 3) score += 20;
    if (values.budget >= m.complexity) score += 15;
    else score += Math.max(0, 15 - (m.complexity - values.budget) * 3);

    return { ...m, score: Math.min(100, Math.round(score)) };
  }).sort((a, b) => b.score - a.score);

  const exportReport = () => {
    const lines = [
      "MODEL SELECTION MATRIX",
      "======================",
      "",
      ...criteria.map((c) => `${c.label}: ${values[c.id]}`),
      "",
      "Ranked Models:",
      ...ranked.map((m, i) => `${i + 1}. ${m.name} (${m.type}) — Fit: ${m.score}%`),
      "",
      `Recommendation: ${ranked[0].name}`,
      "",
      "Generated by Rules for Responsible Modeling — Ch.5 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "model-selection-matrix.txt";
    a.click();
    toast.success("Model selection matrix downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-500 text-white">
          <GitBranch className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Model Selector</h2>
          <Badge variant="outline">Chapter 5</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Define your project constraints and see which model best fits your needs.</p>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-5">
          {criteria.map((c) => (
            <div key={c.id}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-foreground font-medium">{c.label}</span>
                <span className="text-primary font-bold">{values[c.id]}</span>
              </div>
              <Slider min={c.min} max={c.max} step={c.step} value={[values[c.id]]} onValueChange={([v]) => setValues((p) => ({ ...p, [c.id]: v }))} />
            </div>
          ))}
        </Card>

        <div className="space-y-3">
          {ranked.map((m, i) => (
            <Card key={m.name} className={`p-4 ${i === 0 ? "border-primary border-2 bg-primary/5" : ""}`}>
              <div className="flex items-center gap-3">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${i === 0 ? "bg-primary text-primary-foreground" : "bg-secondary text-muted-foreground"}`}>
                  {i + 1}
                </div>
                <div className="flex-1">
                  <p className="font-bold text-foreground text-sm">{m.name}</p>
                  <p className="text-xs text-muted-foreground">{m.type} · Complexity: {m.complexity}/10</p>
                </div>
                <div className="text-right">
                  <span className={`text-lg font-black ${m.score >= 70 ? "text-green-500" : m.score >= 40 ? "text-yellow-500" : "text-red-500"}`}>{m.score}%</span>
                  <p className="text-[10px] text-muted-foreground">fit</p>
                </div>
              </div>
            </Card>
          ))}
          <Button onClick={exportReport} className="w-full gap-2 mt-3">
            <Download className="w-4 h-4" /> Export Selection Matrix
          </Button>
        </div>
      </div>
    </div>
  );
};
