import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Users, Download, ThumbsUp, ThumbsDown, Minus } from "lucide-react";

const reviewItems = [
  { id: "objective", label: "Model objectives clearly defined", category: "Scope" },
  { id: "dataQuality", label: "Input data quality documented", category: "Data" },
  { id: "assumptions", label: "Key assumptions stated", category: "Scope" },
  { id: "paramRange", label: "Parameter ranges justified", category: "Calibration" },
  { id: "calMetrics", label: "Calibration metrics appropriate", category: "Calibration" },
  { id: "valIndep", label: "Validation uses independent data", category: "Validation" },
  { id: "sensitivity", label: "Sensitivity analysis comprehensive", category: "Analysis" },
  { id: "uncertainty", label: "Uncertainty bounds provided", category: "Analysis" },
  { id: "limitations", label: "Limitations honestly stated", category: "Reporting" },
  { id: "reproducible", label: "Model setup reproducible", category: "Documentation" },
  { id: "versioned", label: "Software version documented", category: "Documentation" },
  { id: "peerAccess", label: "Reviewer has model access", category: "Process" },
];

type Rating = "pass" | "concern" | "fail";

export const PeerReviewSim = () => {
  const [ratings, setRatings] = useState<Record<string, Rating>>({});

  const setRating = (id: string, r: Rating) => setRatings((p) => ({ ...p, [id]: r }));

  const passes = Object.values(ratings).filter((r) => r === "pass").length;
  const concerns = Object.values(ratings).filter((r) => r === "concern").length;
  const fails = Object.values(ratings).filter((r) => r === "fail").length;
  const rated = passes + concerns + fails;
  const verdict = fails > 2 ? "Reject" : fails > 0 || concerns > 3 ? "Major Revision" : concerns > 0 ? "Minor Revision" : rated === reviewItems.length ? "Accept" : "Incomplete";
  const verdictColor = verdict === "Accept" ? "text-green-500" : verdict === "Minor Revision" ? "text-yellow-500" : verdict === "Incomplete" ? "text-muted-foreground" : "text-red-500";

  const exportReport = () => {
    const lines = [
      "PEER REVIEW SUMMARY",
      "====================",
      "",
      ...reviewItems.map((item) => {
        const r = ratings[item.id] || "not rated";
        return `[${r.toUpperCase().padEnd(7)}] ${item.label} (${item.category})`;
      }),
      "",
      `Pass: ${passes} | Concerns: ${concerns} | Fails: ${fails}`,
      `Verdict: ${verdict}`,
      "",
      "Generated by Rules for Responsible Modeling — Ch.15 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "peer-review-summary.txt";
    a.click();
    toast.success("Peer review summary downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 text-white">
          <Users className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Peer Review Simulator</h2>
          <Badge variant="outline">Chapter 15</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Rate each review criterion and see the overall verdict — just like a real peer review.</p>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="space-y-2">
          {reviewItems.map((item) => (
            <Card key={item.id} className={`p-3 ${ratings[item.id] === "fail" ? "border-destructive/50" : ratings[item.id] === "pass" ? "border-primary/30" : ""}`}>
              <div className="flex items-center gap-2">
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-foreground">{item.label}</p>
                  <Badge variant="secondary" className="text-[10px] mt-1">{item.category}</Badge>
                </div>
                <div className="flex gap-1 shrink-0">
                  <button onClick={() => setRating(item.id, "pass")} className={`p-1.5 rounded ${ratings[item.id] === "pass" ? "bg-green-500/20 text-green-500" : "text-muted-foreground hover:bg-muted"}`}>
                    <ThumbsUp className="w-4 h-4" />
                  </button>
                  <button onClick={() => setRating(item.id, "concern")} className={`p-1.5 rounded ${ratings[item.id] === "concern" ? "bg-yellow-500/20 text-yellow-500" : "text-muted-foreground hover:bg-muted"}`}>
                    <Minus className="w-4 h-4" />
                  </button>
                  <button onClick={() => setRating(item.id, "fail")} className={`p-1.5 rounded ${ratings[item.id] === "fail" ? "bg-red-500/20 text-red-500" : "text-muted-foreground hover:bg-muted"}`}>
                    <ThumbsDown className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </Card>
          ))}
        </div>

        <div className="space-y-4">
          <Card className="p-6 text-center">
            <p className="text-xs text-muted-foreground mb-2">Review Verdict</p>
            <p className={`text-3xl font-black ${verdictColor}`}>{verdict}</p>
            <div className="flex justify-center gap-4 mt-4 text-sm">
              <span className="text-green-500 font-bold">{passes} ✓</span>
              <span className="text-yellow-500 font-bold">{concerns} ~</span>
              <span className="text-red-500 font-bold">{fails} ✗</span>
            </div>
            <p className="text-xs text-muted-foreground mt-2">{rated}/{reviewItems.length} rated</p>
          </Card>

          <Card className="p-4 text-xs text-muted-foreground space-y-1">
            <p><strong className="text-foreground">Accept:</strong> All pass, no concerns</p>
            <p><strong className="text-foreground">Minor Revision:</strong> ≤3 concerns, 0 fails</p>
            <p><strong className="text-foreground">Major Revision:</strong> &gt;3 concerns or 1-2 fails</p>
            <p><strong className="text-foreground">Reject:</strong> &gt;2 fails</p>
          </Card>

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Review Summary
          </Button>
        </div>
      </div>
    </div>
  );
};
