import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { FileText, Download, CheckCircle2, XCircle } from "lucide-react";

const sections = [
  {
    title: "Executive Summary",
    items: [
      { id: "purpose", label: "Model purpose clearly stated" },
      { id: "keyFindings", label: "Key findings summarized" },
      { id: "limitations", label: "Limitations acknowledged" },
    ],
  },
  {
    title: "Technical Documentation",
    items: [
      { id: "dataDesc", label: "Input data described with sources" },
      { id: "paramJust", label: "Parameter choices justified" },
      { id: "calResults", label: "Calibration results presented" },
      { id: "valResults", label: "Validation results included" },
    ],
  },
  {
    title: "Uncertainty & Sensitivity",
    items: [
      { id: "uncertAnalysis", label: "Uncertainty analysis performed" },
      { id: "sensAnalysis", label: "Sensitivity analysis included" },
      { id: "confBounds", label: "Confidence bounds on predictions" },
    ],
  },
  {
    title: "Presentation Quality",
    items: [
      { id: "figures", label: "Figures clear with proper labels" },
      { id: "tables", label: "Tables formatted with units" },
      { id: "reproducible", label: "Results reproducible from report" },
    ],
  },
];

const allItems = sections.flatMap((s) => s.items);

export const ReportCardBuilder = () => {
  const [checks, setChecks] = useState<Record<string, boolean>>({});

  const toggle = (id: string) => setChecks((p) => ({ ...p, [id]: !p[id] }));

  const totalChecked = allItems.filter((i) => checks[i.id]).length;
  const pct = Math.round((totalChecked / allItems.length) * 100);
  const grade = pct >= 90 ? "A" : pct >= 75 ? "B" : pct >= 60 ? "C" : pct >= 40 ? "D" : "F";
  const gradeColor = pct >= 75 ? "text-green-500" : pct >= 50 ? "text-yellow-500" : "text-red-500";

  const exportReport = () => {
    const lines = [
      "MODEL REPORT QUALITY CHECKLIST",
      "==============================",
      "",
      ...sections.map((s) => [
        s.title + ":",
        ...s.items.map((i) => `  [${checks[i.id] ? "✓" : " "}] ${i.label}`),
        "",
      ]).flat(),
      `Overall Grade: ${grade} (${pct}%)`,
      "",
      "Generated by Rules for Responsible Modeling — Ch.13 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "report-quality-checklist.txt";
    a.click();
    toast.success("Report checklist downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-lime-500 to-green-500 text-white">
          <FileText className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Report Card Builder</h2>
          <Badge variant="outline">Chapter 13</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Check off report components to score your modeling report's completeness.</p>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="space-y-4">
          {sections.map((s) => (
            <Card key={s.title} className="p-4">
              <p className="text-sm font-bold text-foreground mb-2">{s.title}</p>
              {s.items.map((item) => {
                const checked = !!checks[item.id];
                return (
                  <button key={item.id} onClick={() => toggle(item.id)} className={`w-full flex items-center gap-2 p-2 rounded-lg transition-colors text-left ${checked ? "bg-primary/10" : "hover:bg-muted"}`}>
                    {checked ? <CheckCircle2 className="w-4 h-4 text-primary shrink-0" /> : <XCircle className="w-4 h-4 text-muted-foreground/40 shrink-0" />}
                    <span className={`text-sm ${checked ? "text-foreground" : "text-muted-foreground"}`}>{item.label}</span>
                  </button>
                );
              })}
            </Card>
          ))}
        </div>

        <div className="space-y-4">
          <Card className="p-6 text-center">
            <p className="text-xs text-muted-foreground">Report Quality Grade</p>
            <div className={`text-6xl font-black ${gradeColor}`}>{grade}</div>
            <p className="text-lg font-bold text-foreground">{pct}%</p>
            <div className="w-full h-3 bg-secondary rounded-full overflow-hidden mt-3">
              <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${pct}%` }} />
            </div>
            <p className="text-xs text-muted-foreground mt-2">{totalChecked}/{allItems.length} items checked</p>
          </Card>

          {sections.map((s) => {
            const sectionChecked = s.items.filter((i) => checks[i.id]).length;
            const sectionPct = Math.round((sectionChecked / s.items.length) * 100);
            return (
              <div key={s.title} className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground w-32 truncate">{s.title}</span>
                <div className="flex-1 h-2 bg-secondary rounded-full overflow-hidden">
                  <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${sectionPct}%` }} />
                </div>
                <span className="text-xs font-bold w-10 text-right">{sectionPct}%</span>
              </div>
            );
          })}

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Checklist
          </Button>
        </div>
      </div>
    </div>
  );
};
