import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { Expand, Download, AlertTriangle } from "lucide-react";

const scopeItems = [
  { id: "outlets", label: "Number of model outlets", min: 1, max: 20, default: 3 },
  { id: "scenarios", label: "Design scenarios requested", min: 1, max: 15, default: 2 },
  { id: "stakeholders", label: "Stakeholder groups involved", min: 1, max: 10, default: 2 },
  { id: "dataGaps", label: "Known data gaps", min: 0, max: 10, default: 1 },
  { id: "timeline", label: "Project timeline (weeks)", min: 2, max: 52, default: 12 },
  { id: "modelTypes", label: "Model types required", min: 1, max: 5, default: 1 },
];

export const ScopeCreepDetector = () => {
  const [values, setValues] = useState<Record<string, number>>(
    Object.fromEntries(scopeItems.map((s) => [s.id, s.default]))
  );

  const complexity = Math.round(
    values.outlets * 3 +
    values.scenarios * 5 +
    values.stakeholders * 4 +
    values.dataGaps * 6 +
    values.modelTypes * 8 -
    values.timeline * 1.5
  );

  const risk = complexity > 80 ? "Critical" : complexity > 50 ? "High" : complexity > 25 ? "Medium" : "Low";
  const riskColor = complexity > 80 ? "text-red-500" : complexity > 50 ? "text-orange-500" : complexity > 25 ? "text-yellow-500" : "text-green-500";
  const riskBg = complexity > 80 ? "from-red-500" : complexity > 50 ? "from-orange-500" : complexity > 25 ? "from-yellow-500" : "from-green-500";

  const exportReport = () => {
    const lines = [
      "SCOPE CREEP RISK ASSESSMENT",
      "===========================",
      `Risk Level: ${risk} (Score: ${complexity})`,
      "",
      ...scopeItems.map((s) => `${s.label}: ${values[s.id]}`),
      "",
      "Recommendations:",
      complexity > 50 ? "- REDUCE scope: fewer outlets or scenarios" : "- Scope appears manageable",
      values.dataGaps > 3 ? "- ADDRESS data gaps before modeling begins" : "",
      values.timeline < 8 && complexity > 30 ? "- EXTEND timeline or reduce deliverables" : "",
      "",
      "Generated by Rules for Responsible Modeling — Ch.2 Micro-App",
    ].filter(Boolean);
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "scope-risk-assessment.txt";
    a.click();
    toast.success("Scope assessment downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-red-500 to-orange-500 text-white">
          <Expand className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Scope Creep Detector</h2>
          <Badge variant="outline">Chapter 2</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Adjust project parameters to see how scope complexity compounds — and when it crosses into danger.</p>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-5">
          {scopeItems.map((item) => (
            <div key={item.id}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-foreground font-medium">{item.label}</span>
                <span className="text-primary font-bold">{values[item.id]}</span>
              </div>
              <Slider min={item.min} max={item.max} step={1} value={[values[item.id]]} onValueChange={([v]) => setValues((p) => ({ ...p, [item.id]: v }))} />
            </div>
          ))}
        </Card>

        <div className="space-y-4">
          <Card className="p-6 text-center">
            <p className="text-sm text-muted-foreground mb-2">Scope Creep Risk</p>
            <div className={`text-5xl font-black ${riskColor}`}>{risk}</div>
            <div className="mt-2 w-full h-3 bg-secondary rounded-full overflow-hidden">
              <div className={`h-full bg-gradient-to-r ${riskBg} to-transparent transition-all`} style={{ width: `${Math.min(complexity, 100)}%` }} />
            </div>
            <p className="text-xs text-muted-foreground mt-2">Complexity score: {complexity}</p>
          </Card>

          {complexity > 50 && (
            <Card className="p-4 border-l-4 border-l-destructive bg-destructive/5">
              <div className="flex gap-2 items-start">
                <AlertTriangle className="w-5 h-5 text-destructive shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-bold text-foreground">Scope Warning</p>
                  <p className="text-xs text-muted-foreground">
                    {values.dataGaps > 3 && "Too many data gaps. "}
                    {values.scenarios > 8 && "Scenario count is unsustainable. "}
                    {values.timeline < 8 && "Timeline too tight for this complexity."}
                    {complexity > 80 && " Consider phased delivery."}
                  </p>
                </div>
              </div>
            </Card>
          )}

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Risk Assessment
          </Button>
        </div>
      </div>
    </div>
  );
};
