import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { MessageSquare, Download } from "lucide-react";

const audiences = [
  { id: "council", label: "City Council", techLevel: 1 },
  { id: "engineer", label: "Design Engineer", techLevel: 7 },
  { id: "public", label: "General Public", techLevel: 0 },
  { id: "regulator", label: "Regulator", techLevel: 5 },
  { id: "developer", label: "Land Developer", techLevel: 3 },
];

const technicalPhrases: Record<string, { technical: string; translations: Record<number, string> }> = {
  nse: {
    technical: "NSE = 0.82 indicating good model performance",
    translations: {
      0: "Our flood predictions closely match what actually happened — 82% accuracy",
      1: "The model reproduces past floods with 82% accuracy — above industry standards",
      3: "Model accuracy is 82%, meaning predictions are reliable for planning decisions",
      5: "Nash-Sutcliffe Efficiency of 0.82 — acceptable per regulatory guidelines",
      7: "NSE = 0.82 across the calibration period with PBIAS within ±10%",
    },
  },
  uncertainty: {
    technical: "±15% uncertainty in the 100-year ARI peak flow estimate",
    translations: {
      0: "The 'once in 100 years' flood could be 15% bigger or smaller than our best estimate",
      1: "Our flood estimate has a margin of error — the real flood could be somewhat larger",
      3: "Peak flood flow has a 15% margin — design should account for this range",
      5: "Uncertainty band of ±15% on the 1% AEP peak — within acceptable limits",
      7: "Monte Carlo analysis yields ±15% on Q100; 90th percentile = 1.15 × central estimate",
    },
  },
  calibration: {
    technical: "Model calibrated to 3 events with independent validation on 2 events",
    translations: {
      0: "We tested the model against 5 real storms — it passed all checks",
      1: "The model was trained on 3 historic storms and verified on 2 more independently",
      3: "Calibration used 3 events; validation on 2 separate events confirms reliability",
      5: "Calibration dataset: 3 events. Validation (split-sample): 2 independent events",
      7: "Split-sample cal/val: 3-event calibration, 2-event validation; see Table 4 for metrics",
    },
  },
};

export const StakeholderTranslator = () => {
  const [selectedAudience, setSelectedAudience] = useState(audiences[0]);
  const [customTech, setCustomTech] = useState([selectedAudience.techLevel]);

  const techLevel = customTech[0];

  const getTranslation = (phrases: Record<number, string>) => {
    const levels = Object.keys(phrases).map(Number).sort((a, b) => a - b);
    let best = levels[0];
    for (const l of levels) {
      if (l <= techLevel) best = l;
    }
    return phrases[best];
  };

  const exportReport = () => {
    const lines = [
      "STAKEHOLDER COMMUNICATION GUIDE",
      "================================",
      "",
      `Target Audience: ${selectedAudience.label} (Tech Level: ${techLevel}/10)`,
      "",
      ...Object.entries(technicalPhrases).map(([key, p]) => [
        `Technical: ${p.technical}`,
        `Translated: ${getTranslation(p.translations)}`,
        "",
      ]).flat(),
      "Generated by Rules for Responsible Modeling — Ch.16 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "stakeholder-translations.txt";
    a.click();
    toast.success("Communication guide downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-pink-500 to-rose-500 text-white">
          <MessageSquare className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Stakeholder Translator</h2>
          <Badge variant="outline">Chapter 16</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Select an audience and see how technical model results should be communicated to them.</p>

      <div className="flex gap-2 flex-wrap">
        {audiences.map((a) => (
          <Button key={a.id} size="sm" variant={selectedAudience.id === a.id ? "default" : "outline"} onClick={() => { setSelectedAudience(a); setCustomTech([a.techLevel]); }}>
            {a.label}
          </Button>
        ))}
      </div>

      <Card className="p-4">
        <div className="flex justify-between text-sm mb-1">
          <span className="text-foreground font-medium">Technical literacy level</span>
          <span className="text-primary font-bold">{techLevel}/10</span>
        </div>
        <Slider min={0} max={10} step={1} value={customTech} onValueChange={setCustomTech} />
      </Card>

      <div className="space-y-4">
        {Object.entries(technicalPhrases).map(([key, p]) => (
          <Card key={key} className="p-5">
            <div className="mb-3">
              <Badge variant="secondary" className="text-[10px] mb-2">Technical</Badge>
              <p className="text-sm text-muted-foreground font-mono">{p.technical}</p>
            </div>
            <div className="border-t pt-3">
              <Badge className="text-[10px] mb-2">For {selectedAudience.label}</Badge>
              <p className="text-sm text-foreground font-medium">{getTranslation(p.translations)}</p>
            </div>
          </Card>
        ))}
      </div>

      <Button onClick={exportReport} className="w-full gap-2">
        <Download className="w-4 h-4" /> Export Communication Guide
      </Button>
    </div>
  );
};
