import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { Sigma, Download } from "lucide-react";

const sources = [
  { id: "rainfall", label: "Rainfall uncertainty (%)", min: 5, max: 50, default: 15 },
  { id: "roughness", label: "Roughness uncertainty (%)", min: 5, max: 40, default: 20 },
  { id: "imperv", label: "Imperviousness uncertainty (%)", min: 5, max: 30, default: 10 },
  { id: "slope", label: "Slope uncertainty (%)", min: 2, max: 20, default: 5 },
  { id: "soilInfil", label: "Infiltration uncertainty (%)", min: 10, max: 60, default: 25 },
];

const baseFlow = 45; // m³/s

export const UncertaintyRanger = () => {
  const [values, setValues] = useState<Record<string, number>>(
    Object.fromEntries(sources.map((s) => [s.id, s.default]))
  );

  const combined = Math.sqrt(Object.values(values).reduce((s, v) => s + v ** 2, 0));
  const lower = baseFlow * (1 - combined / 100);
  const upper = baseFlow * (1 + combined / 100);
  const rangeWidth = upper - lower;

  const sorted = sources.map((s) => ({ ...s, value: values[s.id] })).sort((a, b) => b.value - a.value);

  const svgW = 360;
  const svgH = 200;
  const cx = svgW / 2;

  const exportReport = () => {
    const lines = [
      "UNCERTAINTY ANALYSIS",
      "====================",
      "",
      `Base flow estimate: ${baseFlow} m³/s`,
      `Combined uncertainty: ±${combined.toFixed(1)}%`,
      `Prediction range: ${lower.toFixed(1)} – ${upper.toFixed(1)} m³/s`,
      "",
      "Source contributions:",
      ...sorted.map((s) => `  ${s.label}: ±${s.value}%`),
      "",
      "Generated by Rules for Responsible Modeling — Ch.12 Micro-App",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "uncertainty-analysis.txt";
    a.click();
    toast.success("Uncertainty analysis downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2.5 rounded-xl bg-gradient-to-br from-violet-500 to-purple-500 text-white">
          <Sigma className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-foreground">The Uncertainty Ranger</h2>
          <Badge variant="outline">Chapter 12</Badge>
        </div>
      </div>
      <p className="text-muted-foreground">Adjust input uncertainties and watch how they compound into prediction bands.</p>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-6 space-y-5">
          {sources.map((s) => (
            <div key={s.id}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-foreground font-medium">{s.label}</span>
                <span className="text-primary font-bold">±{values[s.id]}%</span>
              </div>
              <Slider min={s.min} max={s.max} step={1} value={[values[s.id]]} onValueChange={([v]) => setValues((p) => ({ ...p, [s.id]: v }))} />
            </div>
          ))}
        </Card>

        <div className="space-y-4">
          <Card className="p-5">
            <svg viewBox={`0 0 ${svgW} ${svgH}`} className="w-full">
              {/* Uncertainty band */}
              <rect x={cx - rangeWidth * 1.5} y={40} width={rangeWidth * 3} height={80} rx={8} fill="hsl(var(--primary))" opacity={0.1} />
              <rect x={cx - rangeWidth} y={60} width={rangeWidth * 2} height={40} rx={6} fill="hsl(var(--primary))" opacity={0.2} />
              {/* Center line */}
              <line x1={cx} y1={35} x2={cx} y2={130} stroke="hsl(var(--primary))" strokeWidth={2} />
              <circle cx={cx} cy={80} r={5} fill="hsl(var(--primary))" />
              {/* Labels */}
              <text x={cx - rangeWidth * 1.5} y={140} fontSize={10} fill="hsl(var(--muted-foreground))">{lower.toFixed(1)}</text>
              <text x={cx} y={155} fontSize={11} fill="hsl(var(--foreground))" textAnchor="middle" fontWeight="bold">{baseFlow}</text>
              <text x={cx + rangeWidth * 1.5} y={140} fontSize={10} fill="hsl(var(--muted-foreground))" textAnchor="end">{upper.toFixed(1)}</text>
              <text x={cx} y={20} fontSize={10} fill="hsl(var(--muted-foreground))" textAnchor="middle">±{combined.toFixed(1)}%</text>
              <text x={cx} y={180} fontSize={9} fill="hsl(var(--muted-foreground))" textAnchor="middle">Prediction range (m³/s)</text>
            </svg>
          </Card>

          <Card className="p-5">
            <p className="text-sm font-bold text-foreground mb-3">Uncertainty Sources (ranked)</p>
            {sorted.map((s) => (
              <div key={s.id} className="flex items-center gap-2 mb-2">
                <span className="text-xs text-muted-foreground w-24 truncate">{s.label.replace(" uncertainty (%)", "")}</span>
                <div className="flex-1 h-2.5 bg-secondary rounded-full overflow-hidden">
                  <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${(s.value / 60) * 100}%` }} />
                </div>
                <span className="text-xs font-bold w-10 text-right">±{s.value}%</span>
              </div>
            ))}
          </Card>

          <Button onClick={exportReport} className="w-full gap-2">
            <Download className="w-4 h-4" /> Export Analysis
          </Button>
        </div>
      </div>
    </div>
  );
};
